version: "3.8"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/user/src/app
    environment:
      - PYTHONUNBUFFERED=1
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

  postgres:
    image: joellasmim/fastaoi
    environment:
      - POSTGRES_PASSWORD=1Jossilene%40@
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
